name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Add this if your branch is called 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test application
      run: |
        echo "No tests yet!"

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/ci-cd-flask-app-yuvraj.git
        git push heroku HEAD:master --force
